appName: hisbook-front
replicaCount: 1

namespace: hisbook-front

image:
  name: acemcbmis/hisbook-front
  tag: a5e040a-prod

host:
#  name: hisbook.bata.local
   name: front.192.168.1.210.nip.io
onPrem: true
