appName: hisbook-front
replicaCount: 1

namespace: hisbook-front

image:
  name: jeniel/hisbook
  tag: f3684a2-prod

host:
#  name: hisbook.bata.local
   name: front.192.168.254.160.nip.io
onPrem: true
