apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJhY2VtY2JtaXMiLCJwYXNzd29yZCI6InBAc3N3b3JkQEBjM21jIiwiZW1haWwiOiJtaXNAYWNlbWNib2hvbC5jb20ifX19
  DATABASE_URL: "postgresql://postgres:1234@localhost:5432/acebookv2"
  JWT_SECRET: "ec20x52x2xd4c5xbd7378bde"
  JWT_REFRESH_TOKEN: "asddasd12352224cx5bd73"
  OPENAI_API_KEY: "123123123123123123123123"
  QDRANT_API_KEY: "e3d5f4104d8d76394d142fbffb9d91a0e7f9a73b"
